services:
  web_ui:
    build: .
    container_name: web_ui
    restart: always
    env_file:
      - .env
    ports:
      - 3000:3000
  web_server:
    image: nginx:latest
    ports:
      - 80:80
      - 443:443 
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
  traccar_engine:
    image: traccar/traccar
    ports:
      - 5000-5150:5000-5150
      - 5000-5150:5000-5150/udp
    volumes:
      - logs:/opt/traccar/logs:rw
      - ./traccar/traccar.xml:/opt/traccar/traccar.xml
    restart: always
  postgres:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    restart: always

volumes:
  postgres:
  logs:
  