services:
  web_ui:
    build: .
    container_name: web_ui
    restart: always
    env_file:
      - .env
  web_server:
    image: nginx:latest
    ports:
      - 80
      - 443
    volumes:
      - ./nginx/default.conf:/etc/nginx/nginx.conf:ro
  traccar_engine:
    image: traccar/traccar
    ports:
      - 5000-5150:5000-5150
      - 5000-5150:5000-5150/udp
    volumes:
      - logs:/opt/traccar/logs:rw
      - ./traccar/traccar.xml:/opt/traccar/traccar.xml
  postgres:
    image: postgres:14-alpine
    .env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
  logs:
  